### ISSUE TITLE
implement password generation

### ISSUE THREAD

**Issue by bv-hamanfnn** [Luzifer/ots#100]
Hi,

Thanks for this awesome Project!
I had an idea for a simple password generation in the secret. I have created a first version of this on my system:
![image](https://github.com/Luzifer/ots/assets/85334830/bf09877a-810b-4171-be29-34df2e6677a3)

It uses basic JS code to choose x random characters from a string. An example for that would be: ANk5V0}iQEBw>?L
This is the code I wrote, the length of the password and the characters in it can be changed with customize.yaml
```// generatePassword creates a simple password and adds it to the end of the secret
generatePassword() {
  let characterSet = this.customize.passwordCharacterSet ||
'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~'
  let passwordLength = this.customize.passwordLength || 15
  let password = ''
    
  for (let i = 0; i < passwordLength; i++) {
    password += characterSet.charAt(Math.floor(Math.random() * characterSet.length))
  }

  const secretInput = document.getElementById("secret")
  secretInput.focus()
  secretInput.setRangeText(password)
  secretInput.setSelectionRange((secretInput.selectionStart + passwordLength), (secretInput.selectionStart + passwordLength))
},
```
Would this be a feature that is worth implementing?

**Comment by Luzifer** [comment]
As a first remark:

```javascript
password += characterSet.charAt(Math.floor(Math.random() * characterSet.length))
```

Please **NEVER** use `Math.random()` for secure purposes! That random number generator [is **NOT** cryptographically secure](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random)!

---

In regards of adding a password generator to OTS: I think there are way better tools (i.e. [passwd.fyi](https://passwd.fyi/) using [Luzifer/password](https://github.com/Luzifer/password), Keepass*, Bitwarden, …) to generate passwords (for example have a look at the list of checks my tool applies to the generated password to ensure "dict"-attacks are pointless).

OTS is intended to share secrets (passwords, steam-keys, text, …) in a secure way. Following the [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) - especially sentence one

> Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".

we should not add features out of this scope.

In the end within OTS a [password generator](https://github.com/Luzifer/ots/blob/master/src/app.vue#L354-L356) already exist but only for use as a source for the encryption key and with a much more [limited character set](https://github.com/Luzifer/ots/blob/master/src/app.vue#L281-L282). Sure we **could** expose that generator to fill the secret on its own but this would add even more buttons to the interface and more complexity to the tool.

In regards of the Unix philosophy and the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) ("keep it stupidly simple" - which we already stretched a lot) lets not add this.

**Comment by bv-hamanfnn** [comment]
Hey Luzifer,

thanks for your tips, learnt something new! Looks like I'll remove the password generator from my instance and search for a better option.
