### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by Icikowski** [Luzifer/ots#105]
Howdy! 

I really appreciate using `ots` on daily basis, so I'd like to contribute a little to its internationalization.

The attached [`i18n.yaml`](https://github.com/Luzifer/ots/files/12250122/i18n.txt) file introduces the Polish translation for the application. Looking forward to see it in next release!

P.S. The attachment will have `.txt` extension; as it seems, GitHub does not fancy attaching YAMLs to issues.

**Comment by Luzifer** [comment]
Translations are included in `v1.6.0`! - Thanks again for taking the time to translate and to contribute! 🙂
