### ISSUE TITLE
Feature request: copy all to clipboard button on Reading your secret page

### ISSUE THREAD

**Issue by mshedsilegx** [Luzifer/ots#110]
Would it be possible to implement a button to select all the secret field and copy to client clipboard ?
It would help the recipient users.

**Comment by Luzifer** [comment]
What do you think about this?

![image](https://github.com/Luzifer/ots/assets/20142/55bf2cbf-c2b4-4d55-9a91-d05a256afad6)

(Currently only interface draft, buttons will get colors and stuff… But should work fine don't you think?)

**Comment by mshedsilegx** [comment]
This is perfect


-----

Xavier de Gelis

Principal IT Architect, Global Finance

McKesson Corporation

***@***.******@***.***>

Phone: (281) 863-4608<tel:+12818634608>



Confidentiality Notice: This email message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.

________________________________
From: Knut Ahlers ***@***.***>
Sent: Saturday, August 12, 2023 5:50:39 AM
To: Luzifer/ots ***@***.***>
Cc: De Gelis, Xavier ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [Luzifer/ots] Feature request: copy all to clipboard button on Reading your secret page (Issue #110)

CAUTION: This email was sent from an EXTERNAL source. Use caution when clicking links or opening attachments.
________________________________

What do you think about this?

[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/20142/260222444-55bf2cbf-c2b4-4d55-9a91-d05a256afad6.png__;!!KMayzP4JbQ!ZZS2qEdAWP2--vKPJO0K93mu4ng1C0lE8YDk_ApLg-B7UsexwM0CnqDN08JfGztqp3qIZBwC0jb6xDrECieYgyGZKqso3Q$>

(Currently only interface draft, buttons will get colors and stuff… But should work fine don't you think?)
