### ISSUE TITLE
[Feature request] Add expiry for memory storage

### ISSUE THREAD

**Issue by bendoin** [Luzifer/ots#12]
Suggestions would be to either change the os.Getenv("REDIS_EXPIRY") to os.Getenv("OTS_EXPIRY") or just read that same os.Getenv("REDIS_EXPIRY") for the memory only storage?

**Comment by Luzifer** [comment]
Sounds good to have the secrets in in-mem storage expire like those in Redis does. Will implement. Thank you very much for the suggestion! :slightly_smiling_face:

**Comment by Luzifer** [comment]
Version `v0.17.0` has just been released and contains support for `SECRET_EXPIRY` environment variable on both storage backends.
