### ISSUE TITLE
customize.yml only partially loaded?

### ISSUE THREAD

**Issue by pehbehbeh** [Luzifer/ots#128]
I have the following `customize.yaml`:

```
appTitle: "Example"
disablePoweredBy: true
disableQRSupport: true
disableThemeSwitcher: true
disableFileAttachment: false
maxAttachmentSizeTotal: 4194304
```

For some reason only some of the values are present in the frontend:

```
window.OTSCustomize = JSON.parse('{"appTitle":"Example","disablePoweredBy":true,"disableQRSupport":true,"disableThemeSwitcher":true}')
```

I don't know what I'm doing wrong here - some values are loaded and others are not. 🤷 Am I missing the obvious here? 🤔

**Comment by Luzifer** [comment]
The last two are [`v1.9.x`](https://github.com/Luzifer/ots/milestone/1) options. If you didn't build from `master` branch yourself but used the `v1.8.x` download they aren't available yet (but you can keep them, they will automatically be loaded as soon as you've upgraded to `v1.9.0`…

**Comment by pehbehbeh** [comment]
Oh 🙈 Thats it... Thanks for the quick response!
