### ISSUE TITLE
Paths are saved with the attachments

### ISSUE THREAD

**Issue by mshedsilegx** [Luzifer/ots#135]
Would it be possible to remove the paths from displaying (equivalent of a basename), and to not be part of the dowloaded files ?

![image](https://github.com/Luzifer/ots/assets/32753787/f8953093-acbb-4dea-9937-88d8863ddfe2)
![image](https://github.com/Luzifer/ots/assets/32753787/77906b45-a1d8-4cec-97c9-ae337841a007)

It is altering the filename when saving it during secret retrieval..

**Comment by Luzifer** [comment]
Hmm thats interesting… Did you create the secret through the browser or using OTS-CLI? I've never observed paths to be included when selecting a file in the browser… 🤔

**Comment by mshedsilegx** [comment]
That is correct, the path issue only happens via cli:
-f __PATH__/file

__PATH__ is stored, and becomes part of the file name, with "/" converted to "_"
