### ISSUE TITLE
Add customization and server-side check for total size

### ISSUE THREAD

**Issue by Luzifer** [Luzifer/ots#138]
In order not to only rely on a properly done nginx / proxy configuration we should add a new setting to reject too large payload even when `max_body_size` is set way too big.

- [x] Add customization setting for maximum payload size (think about base64 increase of data size when adding max file size + secret and base64 encode that)
- [x] Add server-side check for size of received data, reject larger secret payloads

**Comment by sorcix** [comment]
The check in 1623e09225a1136b50de4cdebb79e69c399b0a55 is not enough, as it only checks the size after everything has already been read into memory. This means someone could still crash your server by eating up all your memory.

You could use a [LimitedReader](https://pkg.go.dev/io#LimitedReader) as an argument to [`json.NewDecoder`](https://github.com/Luzifer/ots/commit/1623e09225a1136b50de4cdebb79e69c399b0a55#diff-f7bb71ca856c07b3329265f26b1e577e00b71e4792550cf14346bdbe0e7bd18dR59) to stop reading data from `req.Body` once the limit has been reached.

**Comment by sorcix** [comment]
Looks like there's a [MaxBytesReader in net/http](https://pkg.go.dev/net/http#MaxBytesReader) that would be even better.

**Comment by sorcix** [comment]
Replacing the `r.Body` variable with a limited version at the top of `func (a apiServer) handleCreate(res http.ResponseWriter, r *http.Request)` would fix the issue for both the `application/json` as the form (via `r.FormValue`) based versions.

```
r.Body = http.MaxBytesReader(w, r.Body, cust.MaxSecretSize)
```

This would break the custom error response, though.

**Comment by Luzifer** [comment]
Hmm. Aside of that being something to be handled on the Ingress / proxy in front of OTS\*, that does not match the expected behavior.

The customization setting is the length of the secret, not of the decoration around the secret. So  when setting the `maxSecretSize: 10` (10B) the reader would allow `{"secret":` and then cut off the read while `{"secret":"..."}` with `...` being a 10B b64-secret would be fully acceptable.

Sure we could add `len("{\n\"secret\": \"\"\n}\n") = 17` bytes to the limit but that does not cover the FormValue case (which I'm not even sure why past-Luzifer built that as every implementation and documentation uses JSON payloads)…

I'm not sure whether we'd benefit from adding this and after formulating this comment I'm even no longer sure whether to keep 1623e09225a1136b50de4cdebb79e69c399b0a55 or to remove it before releasing as it is misleading and gives a false sense of security. (It might lead admins to just disable the `client_max_body_size` limit on the proxy and rely on the application while the proxy is way better suited to throw away the request.) - Also as the limit by default is disabled when keeping it, it must be set to some useful value…

---

\* OTS does not support SSL and will never directly support SSL so there **MUST** be a proxy and for example in nginx you already have configured the [`client_max_body_size`](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) as the default allows a body of 1m. Sadly Traefik by default does not limit the body size if I read the documentation correctly…

In my case this is present on the ingress:
```yaml
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
```

**Comment by sorcix** [comment]
Would be good to enforce a limit in OTS anyway, even if it's something like 3x the configured maxSecretSize. That won't get in the way but would still prevent the issue. I agree that a proxy in front of OTS should limit the size as well, but I have learned not to expect people to configure their servers correctly.

_I work as a system engineer and get questions like "we hit this limit, why can't you just set it to 100G" almost weekly. Similar customers/users that have permissions to change those settings themselves probably just do it._

**Comment by Luzifer** [comment]
> but I have learned not to expect people to configure their servers correctly

Sad but true… 😆 

Yeah I always **hope** the OPS do their job properly but I really should know better, been in the job long enough…

> even if it's something like 3x the configured maxSecretSize

That's a good Idea. Lets set it to the implicit limit the frontend introduces (64MiB) as a default and double it just as a safe-guard…
