### ISSUE TITLE
Make the secret data optional when using attachments

### ISSUE THREAD

**Issue by sorcix** [Luzifer/ots#148]
In OTS v1.10.0 the "create the secret" button is disabled when you've selected an attachment but not entered a secret. It also doesn't tell you that the empty secret is the issue. This is rather confusing. Could we make entering a secret optional if the user attached a file? Alternatively: could it show a message that you still have to enter a secret?

**Comment by Luzifer** [comment]
Yeah I saw that coming… 😆 

Had that while implementing but ditched it as I based some frontend magic on "secret is present"… …which shouldn't be that hard to remove now as the frontend rewrite is finished…

Will make the secret optional when a file is present.
