### ISSUE TITLE
Prometheus implementation

### ISSUE THREAD

**Issue by xhochn** [Luzifer/ots#15]
Hey,

would it be possible to integrate prometheus? I just don´t wanna fork your go_helpers repo ;)

Kind regards

**Comment by Luzifer** [comment]
This creates questions for me:

- What's the purpose of a "Prometheus implementation"? Do you want to have metrics how often secrets are created?
- Why would you need to fork the `go_helpers` repo?

**Comment by xhochn** [comment]
- My fault, I just had a quick look at your code and thought that the GzipFunc need to be handled.
- Yes i just want to know often secrets are created.

**Comment by Luzifer** [comment]
Having put a thought into this I will not implement this here as it would on the one hand inflate code base and dependencies hugely (Prometheus has quite a lot of dependencies) and on the other hand it would go against the concept (keep-it-simple and especially zero-knowledge) of OTS.

In the end I want users to be able to trust OTS to keep their secrets secret and attaching more and more dependencies - especially metrics - would in my opinion go against this.

Though I won't implement this, you are welcome to create a fork and implement the Prometheus client yourself. You won't need to fork all the dependencies: just the OTS repo itself. All the dependencies you can continue to use from my repos.
