### ISSUE TITLE
how to define a favicon?

### ISSUE THREAD

**Issue by olewaldo** [Luzifer/ots#156]
Hi,

how can I add a favicon? 

Thank you!

**Comment by Luzifer** [comment]
You should be able to put a `favicon.ico` into the `overlayFSPath` specified within your [Customization](https://github.com/Luzifer/ots/wiki/Customization). As the browser asks for that file it should be grabbed and displayed.

```yaml
# Custom path to override embedded resources. You can override any
# file present in the `frontend` directory (which is baked into the
# binary during compile-time). You also can add new files (for
# example the appIcon given above). Those files are available at the
# root of the application (i.e. an app.png would be served at
# https://ots.example.com/app.png).
overlayFSPath: /path/to/ots-customization
```

- Create a folder, put in the icon
- Create a [Customization](https://github.com/Luzifer/ots/wiki/Customization) file
- Set the `overlayFSPath` to the folder
- Start OTS with `CUSTOMIZE=<your file>` or `--customize=<your file>`
