### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by mshedsilegx** [Luzifer/ots#160]
1- Make the default text area taller for secret data issuer and recipient, I would say double vertical size, so users do not have to scroll all the time
2- Some hover text on the 3 buttons on the right to explain what they are, for the Secret Recipient UI
3- [Paste] and [Load from File] buttons for the Secret Issuer UI
4- When clicking on the copy to clipboard button for the Secret recipient UI, I would be great to have a small text saying "Secret Copied" or similar

![image](https://github.com/Luzifer/ots/assets/32753787/244b9d30-532c-46c0-8189-6371a5258da9)

**Comment by Luzifer** [comment]
> 1- Make the default text area taller for secret data issuer and recipient, I would say double vertical size, so users do not have to scroll all the time

I disagree: Just making the box bigger is a huge waste of space. Instead I'm gonna invest some time into making the textareas grow automatically with a minimum of 4 lines or so…

> 2- Some hover text on the 3 buttons on the right to explain what they are, for the Secret Recipient UI

Agreed: Will add titles. (I'm surprised I didn't already… 🤔)

> 3- [Paste] and [Load from File] buttons for the Secret Issuer UI

Hmm here I tend to disagree. For files there is the file-attachment functionality. Peeps will try to load anything then and that will lead to really bad UX. And for a paste-button I don't see the benefit. Clipboard `read` is [not (fully) supported](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#browser_compatibility) throughout all browsers and Ctrl+V / right-click-paste / long-touch-paste is supported everywhere.

> 4- When clicking on the copy to clipboard button for the Secret recipient UI, I would be great to have a small text saying "Secret Copied" or similar

The button flashes green as a confirmation. Too short to notice?

**Comment by Luzifer** [comment]
Changes for 1 and 2 are live on the [ots.fyi](https://ots.fyi/) instance if you want to have a look.

**Comment by mshedsilegx** [comment]
#1 and #2 look good to me.

> The button flashes green as a confirmation. Too short to notice?
I did not notice it before, that's fine then.

**Comment by Luzifer** [comment]
For number 4 increased the time from 500ms to 1500ms and added in the check-mark… …also live now…

**Comment by mshedsilegx** [comment]
All looks excellent, user feedback is very good.
