### ISSUE TITLE
How to use customize.yaml in an azure docker environment?

### ISSUE THREAD

**Issue by tvsucks** [Luzifer/ots#174]
Heyho, How to use the customize.yaml in an azure docker environment? We stored the customize.yaml in a folder called config and tried to use the "Startup file or command": "--customize=/config/customize.yaml" in azure Deployment Center. It doesn't work. Can you assist? Is this the right way? 

Best regards
Franz

**Comment by Luzifer** [comment]
Hm sadly Azure is the only one of the three big clouds I haven't worked with and therefore I have no knowledge about the Azure Deployment Center…

Basically you want to make sure the the file gets deployed to the machine where the container lives and be mounted into the container. If you mount it at `/config/` in the container your argument should work…

If the file gets deployed into a folder on the host-machine the docker is running on, can you specify a mount for the Docker container to mount that folder?
