### ISSUE TITLE
How to redirect logging to a file

### ISSUE THREAD

**Issue by mshedsilegx** [Luzifer/ots#175]
I could not find a reference on how to store the ots output into a file, say /var/log/ots.log
Is there a --log-file-path= option (I see only --log-level)
If not, is this something we could had to the roadmap.
Thank you.

**Comment by mshedsilegx** [comment]
Yes, redirect works too, this is what I have currently. It is much easier to work with text logs than using journalctl for alerts and automation. I use systemd.

**Comment by Luzifer** [comment]
Hmm with systemd I'd suggest to use [`StandardError=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#StandardOutput=) for the unit.

To answer the question: OTS itself does not support configuring logging aside of the `--log-level` / `LOG_LEVEL` and it's not planned as redirecting the logs into different targets can easily be achieved through system-provided methods.

**Comment by mshedsilegx** [comment]
ok, thanks, closing
