### ISSUE TITLE
Allow secret creation to be restricted via one time links

### ISSUE THREAD

**Issue by fblz** [Luzifer/ots#180]
Moved from #177:

It is recommended that people run their own instance of OTS to enhance security.
Since OTS is used to share logins, this will likely happen over the internet.
Therefore, in its current configuration, OTS will be accessible to everyone.
This exposes the operator to at least two risks.
First, illegitimate uploads.
Any open upload could be used to share copyrighted material or even worse content.
If this happens under the operator's domain or server, they could be held liable.
Second, phishing.
A link from an official domain can easily gain the trust of unsuspecting individuals.
Allowing anyone to create such links is a disaster waiting to happen.

To keep the software reasonably simple (and because it would suffice for my use case), I propose two changes.
First, an option to define a "trusted zone," such as an intranet or company IP range, from which it is possible to create OTS shares without further authentication.
Second, an option to create a "request-link" from within the trusted zone.
This request-link would allow anyone who receives it to create exactly one OTS share by including an API token inside the link that is burned on use, just like the secrets themselves.
This approach would allow only trusted people to freely upload secrets yet enable trusted people to request passwords from anyone else on the internet.
The web interface could disable the create option for people not coming from the trusted zone and not having a request-link, by a flag from the /config API mentioned above.

From Luzifer in #177:

> 
> > Uploading needs an authorization system to control uploads.
> 
> #92
> 
> This can be done through the `isWritable` endpoint. It can't be called, the frontend will not display the creation form. It can be called, the frontend will display the creation form. Limit it on the proxy you put in front of the instance by applying access-control to `/api/isWritable` and `/api/create` to only be useable by employees and nobody else can create secrets.

This would not enable employees to request secrets from someone outside the company though, which is the usecase I have.

**Comment by Luzifer** [comment]
Out of scope of the project.

A secret-request-system is a completely different project than OTS. OTS is intended to securely share credentials, not to request them.

You could use a branded instance with locked down creation to send out credentials so peeps know it's coming from your company and you could use an open, unbranded instance for anyone else to share secrets and send them over an identified communication channel to your employees.
