### ISSUE TITLE
Stuck at "Secret is being created..."

### ISSUE THREAD

**Issue by ghebo** [Luzifer/ots#185]
On a fresh deploy in docker (see docker-compose.yaml below) when I try to generate OTS it's stuck at "Secret is being created..."
Noting in logs

docker-compose.yaml
`version: "3.8"
services:
  app:
    image: luzifer/ots:v1.12.0
    restart: always
    environment:
      # Optional, see "Customization" in README
      #CUSTOMIZE: '/etc/ots/customize.yaml'
      # See README for details
      REDIS_URL: redis://redis:6379/0
      # 168h = 1w
      SECRET_EXPIRY: "604800"
      # "mem" or "redis" (See README)
      STORAGE_TYPE: redis
    depends_on:
      - redis
    ports:
      - 3000:3000
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data:/data`

**Comment by Luzifer** [comment]
Without any details I suspect you're experiencing this: https://github.com/Luzifer/ots/issues/184
