### ISSUE TITLE
Problems with customize.yaml

### ISSUE THREAD

**Issue by ipod86** [Luzifer/ots#189]
Hello, 

I would like to adjust the limit for file uploads. To do this, I created the container as follows.

`version: "3.8"
services:
  app:
    image: luzifer/ots:latest
    restart: always
    environment:
      # Optional, see "Customization" in README
      CUSTOMIZE: '/yaml/customize.yaml'
      # See README for details
      REDIS_URL: redis://redis:6379/0
      # 168h = 1w
      SECRET_EXPIRY: "604800"
      # "mem" or "redis" (See README)
      STORAGE_TYPE: redis
    depends_on:
      - redis
    ports:
      - 3001:3000
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data:/data
      - ./yaml:/yaml`
      

On the docker host I can now see the yaml folder. I have saved the example /customize.yaml in this. I should have 115.6MiB there, but it stays at 64.

`
docker@docker:/$ cd data/compose/20/yaml
docker@docker:/data/compose/20/yaml$ dir
customize.yaml
docker@docker:/data/compose/20/yaml$`

Edit 

I've now seen that the yaml isn't found. Other spellings don't help either. I've also looked at the file size again. Unfortunately my English isn't that good. Over 64mb doesn't work so well?

**Comment by Luzifer** [comment]
Please see the explanation in https://github.com/Luzifer/ots/issues/176

**Comment by ipod86** [comment]
My question was how to correctly integrate the yaml. 

It is never found. 
That's why I posted my docker compose. 
Where is the error? 

As for the file size, I don't quite understand whether it can go over 64mb. 
I've already read the posts. The Google translator doesn't translate the text well (I use it because I don't speak English well). 
A yes, more is possible or a no is enough for me.

**Comment by Luzifer** [comment]
After formatting your compose-file above it seems you put the `volumes` directive into the `redis` service definition. If the OTS container should be able to see the files it needs a `volumes` directive itself. See https://docs.docker.com/compose/compose-file/07-volumes/

No, as described in the other issue it is not possible to go over 64M of attachment size as for frontend reasons. The frontend will always limit to 64M (as bigger files will just crash the frontend).

**Comment by ipod86** [comment]
Thanks, it works now. 
Are there any format requirements for the app icon? 
`appIcon: /yaml/icon.png` 
doesn't work. The values ​​with true and false work perfectly.

I'll try my hand at CSS one of these days. I'm excited to see what happens 🤣 I'd like to change the light blue.

**Comment by Luzifer** [comment]
Please see the options `overlayFSPath` and `appIcon` in the [Customization Wiki Page](https://github.com/Luzifer/ots/wiki/Customization)

i.e. you'd set `overlayFSPath: /yaml/assets`, put the icon in `/yaml/assets/icon.png` and set `appIcon: assets/icon.png`.

**Comment by ipod86** [comment]
![Screenshot_20240812_121302_RaspController](https://github.com/user-attachments/assets/f6c6315b-f42b-41dd-a3df-ec81a29a0dbc)

![Screenshot_20240812_121337_RaspController](https://github.com/user-attachments/assets/2e572c62-a087-417b-b202-185c522c85f3)


![Screenshot_20240812_121349_Chrome](https://github.com/user-attachments/assets/99f02726-1d8f-49d5-9381-f83de2c89dc4)

**Comment by Luzifer** [comment]
> and set `appIcon: assets/icon.png`

**Comment by ipod86** [comment]
Yes, now everything works. 

The image is there and the CSS is working. 

Can you tell me where the original CSS is that makes everything look normal. I can then work on it? 

The style.scss is very short.
