### ISSUE TITLE
How to make OTS available through HTTPs?

### ISSUE THREAD

**Issue by luisrome18** [Luzifer/ots#19]
Hello,

How do I get the release to work through HTTPS on Windows or Linux?

Thanks

**Comment by Luzifer** [comment]
On Windows I can't tell you, on Linux you can put [stunnel](https://www.stunnel.org/) or a webserver with proxy capabilities (like [nginx](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/)) in combination with [LetsEncrypt](https://letsencrypt.org/) certificates in front of it.

This is the nginx configuration used for `ots.fyi`:

```nginx
  server {
    listen        443 ssl http2;
    listen        [::]:443 ssl http2;
    server_name   ots.fyi;

    ssl_certificate     /data/ssl/nginxle/ots.fyi.pem;
    ssl_certificate_key /data/ssl/nginxle/ots.fyi.key;

    location / {
      proxy_pass http://127.0.0.1:1640;
    }
  }
```

Same could work on Windows but you'd need to have a look at it.

**Comment by luisrome18** [comment]
I used nginx with your example and it works thank you.
