### ISSUE TITLE
Feature Request: Legal notice and data protection

### ISSUE THREAD

**Issue by ipod86** [Luzifer/ots#191]
Is it possible (optional) to include a link to the legal notice and data protection on all pages? The link must of course be freely definable. In Europe, it is a legal requirement that this information must be accessible from every page in order to operate a website legally.

Something like the bottom left of this picture:

![JPEG_20240912_151745_8709639815815993231](https://github.com/user-attachments/assets/34fd8a3a-ae2a-4773-8705-4388bbca1da0)

**Comment by Luzifer** [comment]
@ipod86 please have a look at the attached PR #192 - that would be an easy way to solve this. You can freely choose the URL and the name so any legal obligations can be fulfilled.

**Comment by ipod86** [comment]
Thank you, 

I couldn't find that. Where do I have to insert it? In the docker compose or the customize.yaml?

**Comment by Luzifer** [comment]
It's not yet released but after it is will be added to the `customize.yaml`.
