### ISSUE TITLE
Additional customisations

### ISSUE THREAD

**Issue by blauwkeut** [Luzifer/ots#203]
I would like to post two additional enhancement requests following 'issue' #71 :

- While you're offering the option to change app.css via the overlay filesystem, if you want to make minor CSS changes to the default bootstrap code, this would require creating the whole CSS file from scratch (unless I misunderstand the mechanics behind app.css).

So would it be possible to allow to just load an additional CSS file using the file overlay system after app.css? If I e.g. want to change the font size of one specific item, or just the background color of the header, I could just override those rather than recompile the whole bootstrap CSS.

- The second request, is for a way to allow to have two logo files - one for light mode, one for dark mode. I tried using CSS @media prefers-color-scheme and the invert() function - but that seems to use the dark/light mode setting of the browser, not the bootstrap dark/light toggle.

Would something like this work?
`<picture>
    <source srcset="dark-image.png" media="(prefers-color-scheme: dark)">
    <img src="light-image.png">
</picture>
`

**Comment by Luzifer** [comment]
The dark-mode does not work through the media-query: it utilizes the Bootstrap 5.3 theme toggle (`data-bs-theme="light"` vs. `data-bs-theme="dark"` see https://github.com/Luzifer/ots/blob/master/frontend/index.html#L36-L43) so if you write a CSS style matching `html[data-bs-theme="dark"]` you should be able to use the invert function.

As of just overwriting parts of the CSS I'd not recommend it: The CSS is a generated and minified version of the upstream CSS and might not have stable identifiers. (In theory and from looking at the delivered code on my hosted instance it uses the original classes but that might change in the future depending on the CSS transpiler.)

If you want to modify the HTML you can put an `index.html` into your overlay dir. The overlay-dir overlays the whole embedded assets (https://github.com/Luzifer/ots/blob/master/main.go#L83-L91) and the index-template is loaded from that overlayed dir (https://github.com/Luzifer/ots/blob/master/main.go#L110-L115). So if you put an index.html with modifications in the root of your overlay dir it overwrites the embedded index and you could load an additional CSS file. Just remember to include the SRI template like for the original file (https://github.com/Luzifer/ots/blob/master/frontend/index.html#L17-L22).

---

As for having different logo image files for light and dark… 🤔 We would need another customization option and then based on whether the theme is set to light or dark the corresponding key is used to display the image…

May I ask for the use-case for this? Most brandings I know would just use the company logo and they are done with it…

**Comment by blauwkeut** [comment]
Thank you for your response, for the first one I'll have a go with your pointers.

For the logo, in my case it's a transparent black or white logo (hence I was trying the invert function). But the black version doesn't really work in night mode, and the white version not in the day mode:
![Screenshot 2024-12-05 141356](https://github.com/user-attachments/assets/99c0fbfa-4dc1-431d-bb96-d5a38c5c3333)
![Screenshot 2024-12-05 141412](https://github.com/user-attachments/assets/0a5c22b2-0f99-49a5-aaa2-72ddaaa99ede)
![Screenshot 2024-12-05 141605](https://github.com/user-attachments/assets/16a51dd2-4127-4486-8ed6-255da27580cc)

**Comment by Luzifer** [comment]
Please have a look at the example in #204 - I think that exactly fits your need, doesn't it?

**Comment by Luzifer** [comment]
Well, your script basically does the same thing as the new customization option… …just in a different way… :D - I'll go ahead and merge the new option in then.

**Comment by blauwkeut** [comment]
Different ways leading to Rome... :) Thanks for considering and implementing, appreciated...
