### ISSUE TITLE
Loading Blank Page with IE 11 

### ISSUE THREAD

**Issue by luisrome18** [Luzifer/ots#22]
Hi,

I have downloaded the current release and noticed that when using IE11 it only brings up a blank page. This also occurs on "https://ots.fyi/". I see this error when investigating ": Unable to get property 'apply' of undefined or null reference", app.js (68,58522).

Thanks,

**Comment by Luzifer** [comment]
Hey, the reason for this is quite simple: The build process does not optimize the Javascript code (which is way too new for the old IE11 engine) for IE11 compability. IE11 is therefore not a supported browser.

Though Microsoft themselves still support IE11 until Windows 10 reaches EOL they recommend using Microsoft Edge (which can access OTS) as the default browser. So I'll follow that recommendation: Please use MS Edge / Chrome / Firefox / Opera in recent versions.
