### ISSUE TITLE
flag provided but not defined: -md5checksum on installation

### ISSUE THREAD

**Issue by ion-lane** [Luzifer/ots#27]
Hello!

I get an error when trying to install with `make`.

>...
> `+` chown -R 0 ../frontend node_modules
> go generate
> flag provided but not defined: -md5checksum
> Usage: go-bindata [options] <input directories>
> 
>   -debug
>         Do not embed the assets, but provide the embedding API. Contents will still be loaded from disk.
>   -dev
>         Similar to debug, but does not emit absolute paths. Expects a rootDir variable to already exist in the generated code's package.
>   -ignore value
>         Regex pattern to ignore
>   -mode uint
>         Optional file mode override for all files.
>   -modtime int
>         Optional modification unix timestamp override for all files.
>   -nocompress
>         Assets will *not* be GZIP compressed when this flag is specified.
>   -nomemcopy
>         Use a .rodata hack to get rid of unnecessary memcopies. Refer to the documentation to see what implications this carries.
>   -nometadata
>         Assets will not preserve size, mode, and modtime info.
>   -o string
>         Optional name of the output file to be generated. (default "./bindata.go")
>   -pkg string
>         Package name to use in the generated code. (default "main")
>   -prefix string
>         Optional path prefix to strip off asset names.
>   -tags string
>         Optional set of build tags to include.
>   -version
>         Displays version information.
> main.go:3: running "go-bindata": exit status 2
> make: *** [Makefile:15: generate] Error 1
> 

```
# go version
go version go1.11.6 linux/amd64
```
```
# go-bindata -version
go-bindata 3.1.0 (Go runtime go1.11.5).
```
Tested on the latest Debian and Ububtu distributions.
Help me install ots.

**Comment by ion-lane** [comment]
> "**Please** help me […]" would be a lot more polite.

Sorry, I don't speak English

>  go get -u github.com/shuLhan/go-bindata/cmd/go-bindata
>  go-bindata -version 
> go-bindata 3.4.0 (Go runtime go1.12.5).
> Copyright (c) 2010-2015, Jim Teeuwen.

I installed go -bindata. Thanks.

Please help me to run ots.
I compiled the program using `make`, but I get an error when running main.go.

```
# go run main.go
# command-line-arguments
./main.go:50:16: undefined: getStorageByType
./main.go:54:9: undefined: newAPI
./main.go:77:20: undefined: Asset
```
OS: Debian 10
Go: go1.15.2
go-bindata: 4.0.0 (Go runtime go1.15.2)

**Comment by Luzifer** [comment]
Please do a `go build` and afterwards use the compiled `./ots` binary… `go run main.go` is not how you run a Go program…

**Comment by ion-lane** [comment]
It works! Many thanks!

**Comment by Luzifer** [comment]
Thats good to hear!
