### ISSUE TITLE
Add support for reverse-proxy on a given path

### ISSUE THREAD

**Issue by toindev** [Luzifer/ots#4]
Add support for a proxy configuration so OTS can be hosted like https://host/ots

(We plan to do it during our weekly workshop at my company)

**Comment by Luzifer** [comment]
I think the easiest way to achieve this would be to ensure all assets are loaded through relative paths. Then the proxy can mount the application where ever it wants.

**Comment by Luzifer** [comment]
Fixed since v0.13.1
