### ISSUE TITLE
Missing CSS in builds on Github releases page

### ISSUE THREAD

**Issue by sorcix** [Luzifer/ots#44]
Frontend code tries to load `/css/all.min.css` which is not included in the builds available on the Github releases page. (Same issue on the hosted version at https://ots.fyi/)

The files exist (and are embedded in the binary) when I build OTS myself.

I see the `css` and `webfonts` folders are in gitignore, is it possible they're ignored for your builds that way?

**Comment by Luzifer** [comment]
Thanks for the notice!

Fixed in the container and should be fixed in the compiled binaries with version `v0.20.1`.

**Comment by Luzifer** [comment]
Checked the linux-amd64 binary: Fixed there too!
