### ISSUE TITLE
Adding integrity attributes to scripts and stylesheets

### ISSUE THREAD

**Issue by sorcix** [Luzifer/ots#46]
I'm looking into adding `integrity=''` attributes to the stylesheet and javascript files in `index.html`.

We can change `index.html` to a Go template and parse it on startup. There's already a conditional for `/` in the assetDelivery function so we can render the template there. There's already an unused `assetSRIHash` in `tplFuncs.go` that can be modified to cache the hashes for embedded assets.

Am I right in thinking that `index.html` is a static file, not generated by the nodejs/vue code?

Then there are also a few font files that are loaded by the stylesheet (or possibly javascript). I'm not sure there's a way to add integrity hashes to those.

**Comment by Luzifer** [comment]
> Am I right in thinking that `index.html` is a static file, not generated by the nodejs/vue code?

That's correct. The file can easily be changed to a Go template in order to use `assetSRIHash` which then can be used to embed SRI hashes for all embedded assets…

I can take this task and while doing so add the external fonts to the embed. Those shouldn't exist…
