### ISSUE TITLE
Use distroless/go for the Docker image

### ISSUE THREAD

**Issue by toindev** [Luzifer/ots#5]
Check the compatibility and use Google distroless go image to reduce size and attack surface.

(We plan to do it during our weekly workshop at my company)

**Comment by Prophecy67** [comment]
This should definitely work. I've got this as a working concept.
```
FROM golang
WORKDIR /go
RUN go get gopkg.in/Luzifer/ots.v0
WORKDIR src/gopkg.in/Luzifer/ots.v0/
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM scratch  
COPY --from=0 /go/src/gopkg.in/Luzifer/ots.v0/main /main
ENTRYPOINT ["./main"]
```

**Comment by Luzifer** [comment]
```
luzifer/ots     latest     0f52edc23446     3 hours ago       18.9MB
<none>          <none>     9a9b3b7febf2     8 seconds ago     12.7MB
```

Using `scratch` with only the binary inside would only mean a 6.2M reduction but a loss of any components possibly usable for later addition of additional storage providers requiring certificates or similar.

I had a look at the `gcr.io/distroless/base` image and the build process is totally intransparent: There is no `Dockerfile` but a `bazel` build loading stuff from some rulesets.

So for now the build in this repo will stay using `alpine` as its base.

If you want not to have the `alpine` base in the image you're using, I'm adding a `Dockerfile.minimal` to the repo you can use to `docker build -f Dockerfile.minimal .` an image without an `alpine` base.
