### ISSUE TITLE
How to set a default language?

### ISSUE THREAD

**Issue by jorgeegomez** [Luzifer/ots#53]
All of my intended users will have one language in common. Is it possible to define this setting for the frontend somewhere, short of re-compiling?

**Comment by Luzifer** [comment]
The language is auto-selected based on the browser settings of the visitor… If you set your browser to German as a preferred language, the frontend is displayed in German… Same with the other languages.

The fallback language in case the user for example specifies Japanese (something we don't have yet) is hard-coded: English ([main.js#L21-L22](https://github.com/Luzifer/ots/blob/master/src/main.js#L21-L22)). So in short: To change the fallback language you would need to re-compile but that shouldn't be required as every user (with a language setting existing in the app - one of ca, de, en, es, fr, lv, nl) is provided with their preferred language.

If the language you're talking about is not yet supported and you are interested in adding it you can translate the [english version](https://github.com/Luzifer/ots/blob/master/src/langs/en.json) and I will happily add it!
