### ISSUE TITLE
password protection in web UI

### ISSUE THREAD

**Issue by mosajjal** [Luzifer/ots#59]
Hi, 

is there a UI component currently available to enable optionally protecting the secret with a password like the way CLI has?

**Comment by Luzifer** [comment]
The secret is always encrypted using a password when using the web-interface. The plain text secret is never sent to the server.

If you have a look at the link generated when creating a secret:

```
https://ots.fyi/#a68120bb-7f5d-4a9d-bfc6-32308e0398a5%7Cyefagouz2ll
```

You can see the `%7C` which is an URL encoded `|` so basically you do have an UUID and a password in the URL (which again is never sent to the server). In this case the secret is stored in the API as `a68120bb-7f5d-4a9d-bfc6-32308e0398a5` and the decryption password is `yefagouz2ll`.

Providing a password manually is not implemented.

Out of interest: Of which CLI are you speaking? There is no "official" CLI for this project… 🤔

**Comment by mosajjal** [comment]
Ah I see didn't pay attention to that. Thanks for confirming that it's not possible to provide the password manually. As for CLI, O was referring to my aliases for `curl` lol
