### ISSUE TITLE
Adding additional information to the popup

### ISSUE THREAD

**Issue by binlab** [Luzifer/ots#62]
It may be useful to add information in the popup when and by whom (e.g. `IP-address`, `User-Agent`) the link to the secret was compromised (or simply opened by chance). It can be useful for both security and debugging

**Comment by Luzifer** [comment]
For this details about the secret must be stored after the secret is already destroyed. Also this would be a GDPR violation as an IP-address is personal data. Also the usefulness of this is questionable: You will get the IP address from it but you cannot do anything with it.

In both senses (zero knowledge principle and GDPR compliance) I'd rather not build this in.

From a SEC perspective: If you get the "there is no secret" screen assume the secret was compromised and ask the sender to re-generate and invalidate the old one.
