### ISSUE TITLE
White site when accessing 

### ISSUE THREAD

**Issue by DraneLixX** [Luzifer/ots#65]
Hi i get a blank white site when friends try to access, also i just get a blank white page on my phone
What should i provide to debug and where to find it?

**Comment by Luzifer** [comment]
Hey,

- where exactly do you get a blank page? On my hosted instance? Did you compile the application yourself?
- Do you have a Javascript blocker active? (JS needs to be allowed)

**Comment by DraneLixX** [comment]
I do selfhost it behing a nginx proxy manager and i get blank page on my phone, in my browser it works fine no Javascript blocker 
In Chrome it looks blank: 
![OTS Blank](https://user-images.githubusercontent.com/33241086/192516348-404da19e-ee4c-476c-9dd0-ae36b68ba071.jpeg)

And Firefox work's fine?
![OTS Blank 2](https://user-images.githubusercontent.com/33241086/192516466-f098a1a0-0b8b-4b64-9428-bf7ea9cbd32e.jpeg)

**Comment by Luzifer** [comment]
![image](https://user-images.githubusercontent.com/20142/192523435-2498b330-aeec-446e-bb43-ababf0279340.png)

Something is modifying the Javascript being delivered. I suppose that "something" is Cloudflare. As OTS is designed with security in mind the Javascript file must not be loaded when modified between the server and the client: Chrome (for me also on desktop) is acting correctly by blocking a modified file. (Firefox should be ashamed to load the file even though the integrity checksum doesn't match.)

Try removing CloudFlare (or any other service modifying files) in between the server and the client (so the client accesses the server without the files being modified).

**Comment by DraneLixX** [comment]
That's sad :( don't want to expose the IP of the server, a few releases ago it was working fine with chrome.
I tried removing the Cloudflare Proxy, seems to have no effect? Also deleted cookies and reloaded the website, still nothing
Could it be that Nginx Proxy Manager makes the trouble? I'm running the Proxy on another server, then OTS itself?

**Comment by Luzifer** [comment]
Works fine on your domain for me now… (Maybe CF needed a moment to adjust stuff, probably DNS timeouts…)

`v0.22.0` is the first one to have the SRI checks built in… So yeah, previous versions were able to run manipulated code…

**Comment by DraneLixX** [comment]
Work's for me now to, sorry for my lack of patience.
Hm so i rly need to expose the real IP of the host.
Thank's for the help to debug it :)

**Comment by Luzifer** [comment]
If you can configure your CF proxy not to modify any files you could continue to use it (though I personally have a strong opinion against CF)… It's just about not modifying the files transmitted by the server until they arrive at the browser.
