### ISSUE TITLE
Can't show favicon on html

### ISSUE THREAD

**Issue by ThekingMX1998** [Luzifer/ots#75]
After I add an icon tag in it. In console, it shows 

`Refused to load the image '<ImageURL>' because it violates the following Content Security Policy directive: "img-src data: 'self'".`

![image](https://user-images.githubusercontent.com/79040577/222971876-68fe765d-8520-46cc-8b71-97126c316feb.png)

**Comment by Luzifer** [comment]
That's expected behavior.

Loading assets from some random remote site (in this case Github) can compromise integrity of the application and therefore is blocked through the CSP.
