### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by ItsMeMistral** [Luzifer/ots#78]
Hi, I am currently looking into onetimesecret.
I am not familiar with coding and the languages and have no clue on how to install and run the code. 
So the current setup process described in README.md won't really help me.

I have been trying a bit reading old issues that might help, haven't been able to get it working.
I am currently using ubuntu server ubuntu-22.04.2 (64bit).
sudo apt-get install build-essential
sudo apt-get install ntp libyaml-dev libevent-dev zlib1g zlib1g-dev openssl libssl-dev libxml2 libreadline-gplv2-dev
sudo apt-get install ruby redis ruby-bundler ruby-dev
sudo apt install golang-go
sudo apt install go-bindata

Somethings still installed from the last onetimesecret I tried. (that didn't work for me)

Could anyone help me do the initial setup? 
The initial setup could also be documented in README.md to make it easier to install for noobs like me :)

Thank you in advance.

**Comment by Luzifer** [comment]
The easiest way would be to start with the [Releases](https://github.com/Luzifer/ots/releases) here on Github, download the latest available binary (which is currently v0.23.0 - need to have a look why v0.24.0 has no binaries) and start it:

```console
# curl -sSfL https://github.com/Luzifer/ots/releases/download/v0.23.0/ots_linux_amd64.tar.gz | tar -xz
# ./ots_linux_amd64 # Open localhost:3000
```

---

For installing from source the [`Dockerfile`](https://github.com/Luzifer/ots/blob/master/Dockerfile) is a good hint… This requires a large amount of packages to be installed on the system and during building I noticed the packages on Ubuntu 22.04 are outdated enough (`nodejs` <14) to break the build process. 🙁 

If you want the binary built on your system and have Docker installed I'd suggest to use the binary built in the Docker environment:

```console
# git clone https://github.com/Luzifer/ots.git
# cd ots
# docker build .
...
Successfully built 29f5e7fcd708
# docker run --rm -ti -v $(pwd):$(pwd) -w $(pwd) --entrypoint sh 29f5e7fcd708 -c 'cp /usr/local/bin/ots .'
# ./ots # Open localhost:3000
```
