### ISSUE TITLE
Shortened URL

### ISSUE THREAD

**Issue by HappyMan4** [Luzifer/ots#83]
Would it be possible to shorten the url? Like when using the bitly url shortener service?
Maybe with an additional click to use an internal shortener service (more work for you) or to use an external url shortener service?

**Comment by Luzifer** [comment]
It is possible to use an URL shortener (tested with Bitly) to shorten the link but I'd advice against it and will not implement:

The URL consists of `<schema>://<host>/#<secret-id>|<encryption-pass>` (`https://ots.fyi/#0e2976bd-c03a-46ab-a86b-a9c2901aec8b|4pCyA3vr8zMan8O87PvN`). Therefore the shortener would create a short-link for a single-use link (which is essentially a waste of resources on their side) and get a copy of the passphrase (which isn't that bad as fetching the secret would invalidate it and cause the recipient to notice it is already gone and probably leaked).

Having an internal shortener would make the passphrase available to the server which goes against the zero-knowledge principle OTS is built on. In this case the operator of the service could fetch the passphrase and secret from the shortener database and create a copy of all stored secrets in plain text without triggering the secret removal by accessing the database directly. As a user you wouldn't have any guarantee your secret is indeed kept safe as nobody would notice this.

**Comment by HappyMan4** [comment]
Thank you for your good explanations. You are right, both alternatives aren't really good so it's better to go with the longer links. That shouldn't be a problem at all, from my first view more shortened urls would have been nice, but definitely not inevitable.
