### ISSUE TITLE
No secret URL is being created

### ISSUE THREAD

**Issue by HappyMan4** [Luzifer/ots#84]
Hello everybody, after downloading and executing the binary of ots_linux_amd64.tar.gz and landing on the clear http page on port 3000 I'm experiencing this problem:
I can't execute the button so that I get the URL with the encrypted data. 😱
What am I doing wrong?
System: Ubuntu Server 22.04.2 LTS (fresh installation, test system)
I'm using this command to run the program: ./ots_linux_amd64 > ots.log 2>&1 &
I'm executing this as root (yes, I know) on my test server.

As I have no clue why it's not working maybe I can get some help here. 👍

**Comment by HappyMan4** [comment]
Hey Luzifer, thanks a lot for your quick response.
I just kept on going forward. Setup an nginx proxy in front, configured it and finally installed an letsencrypt cert with certbot.
Now it's working like a charm.
To answer your question I didn't try the browser console searching for errors.
Thank you for this software, makes me sleep a lot better. ✅😊👍
The rest is just getting the server ready for production use, so optimizing and a bunch of hardening stuff.

**Comment by Luzifer** [comment]
> Thank you for this software, makes me sleep a lot better. :white_check_mark: :blush: :+1:

That's great to hear it provides value for you and you like it! 🙂 - Thank you very much!

**Comment by k0nstntn** [comment]
Hi!
First of all, thank you for your work.
I'm trying to get v1.12.0 running in a local VM on my Computer (./ots ).  I cannot get past "**Secret is being created...**"  
In The DevTools I get the following error:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'importKey')
    at Af (app.js:14:63943)
    at Hy (app.js:14:64250)
    at Object.By [as enc] (app.js:14:63678)
    at app.js:14:68909
```
I tried Chrome, Firefox, Safari.

The old version (v0.25.0) works fine!
Thanks

**Comment by Luzifer** [comment]
@k0nstntn Please create a new issue instead of reviving an issue closed 11 months ago.

I'd guess you're accessing the webinterface through http, not https - correct? The Web-Crypto-API is not available in non SSL-contexts. You need to either call it through `localhost` or a HTTPs connection.

**Comment by k0nstntn** [comment]
ok. Sorry. You helped me already. Works fine with HTTPS!
