### ISSUE TITLE
Disallow creating empty secret

### ISSUE THREAD

**Issue by HappyMan4** [Luzifer/ots#86]
Hi Luzifer, would it be possible to suppress or disallow the possibility to create empty secrets?
When hitting the "create secret" button without typing in something it creates a secret (you can see it in redis db) and you can open the secret url and display the secret. The secret won't show, because there is no, but when trying for the second time you'll get the error page that this secret doesn't exist.
Looking at redis db the empty secret is gone after visiting the secret url page.
Can someone reproduce this problem, please?

**Comment by mshedsilegx** [comment]
I can reproduce exactly as you described.

**Comment by HappyMan4** [comment]
> I can reproduce exactly as you described.

Thank you for reporting back! 😊👍

**Comment by Luzifer** [comment]
Luckily this was an easy one… Will be included in the next release!

**Comment by HappyMan4** [comment]
Whohoo, blazing fast, thanks a lot! ✅🥳👍 Again, great project, so keep going. Think it's got huge potential.
