### ISSUE TITLE
Veracode Scan

### ISSUE THREAD

**Issue by mshedsilegx** [Luzifer/ots#87]
Hello @Luzifer 
Just making sure you were ok for us to perform a veracode scan against the latest source code and share the findings privately as needed.
Please let me know if you have any objections.
Best regards.

**Comment by Luzifer** [comment]
Go ahead! In the end if something is found we'll all profit by fixing the issues…

**Comment by mshedsilegx** [comment]
I agree. What is the best way to relay eventual findings to you for review ?

**Comment by Luzifer** [comment]
Just send me an email to the address [found all over the project](https://github.com/Luzifer/ots/blob/master/LICENSE#L189)!

**Comment by Luzifer** [comment]
Inspired of this also added CodeQL scanning and fixed the one issue it found… So the question alone brought improvement… 🙂

**Comment by mshedsilegx** [comment]
Very good. Would you share the build process you typically use to fully build the executable for Linux ? I will need to submit the resulting binary to veracode, and would like to use the latest possible sources. Much appreciated.

**Comment by Luzifer** [comment]
I think the easiest documentation of the build is inside the [Dockerfile](https://github.com/Luzifer/ots/blob/master/Dockerfile#L9-L23). If you replace `go install` with `go build` at that point you will get the binary in the source directory.

If you don't have a system / container with NodeJS Fermium you can use this to achieve the build (for `make generate` it will use a Docker container):
```
make generate download_libs generate-apidocs
go build -ldflags "-X main.version=$(git describe --tags --always || echo dev)" -mod=readonly
```

The [release workflow](https://github.com/Luzifer/ots/blob/master/.github/workflows/test-and-build.yml#L56-L62) just executes `make publish` which  uses the [`golang.sh`](https://github.com/Luzifer/github-publish/blob/master/golang.sh) build helper script to execute the builds for different environments after executing the other make targets.

**Comment by mshedsilegx** [comment]
Thank you, I was able to build fine with option #2. I will be submitting shortly 1.0.0-d3e92c7 to veracode with related binary

**Comment by mshedsilegx** [comment]
Veracode static scan score of 98 which is outstanding ! I will send you privately the findings.
