### ISSUE TITLE
Secret are not being stored in redis

### ISSUE THREAD

**Issue by mshedsilegx** [Luzifer/ots#88]
1.0.0-d3e92c7
export REDIS_URL="redis://auth:XXXXXXXXXXXXX@127.0.0.1:6379/0"

Secrets are not being stored correctly, internal error as seen below.
POST /api/create" 500 
Reverting to storage type mem fixes the issue.

Previous release 1.0.0-413ad34 worked just fine with 
export REDIS_URL="tcp://auth:XXXXXXXXXXXXX@127.0.0.1:6379/0"

**Comment by mshedsilegx** [comment]
The issue was due to the new redis library.
export REDIS_URL="redis://default:XXXXXXXXXXXXX@127.0.0.1:6379/0"

The auth predicate does not work anymore, probably due to the ACL change in redis 6.x

**Comment by mshedsilegx** [comment]
All is good now, so closing.

**Comment by Luzifer** [comment]
Interesting catch… Still working with `redis:5` on my side (in which `auth:pass` is fine)… Is that something the Redis documentation will tell or shall I add this to the readme?

**Comment by mshedsilegx** [comment]
I think we should add to the readme. I had the issue with redis 7.x, unfortunately I do not have redis 6.x. auth:pass did not work anymore with the new golang redis library of OTS (500 error). I had to replace it with default:pass in the REDIS_URL variable.
I am using the following in /etc/redis/redis.conf: requirepass XXXXXXX

**Comment by Luzifer** [comment]
Interesting… Seems there was a change with Redis 6 which causes this:
```golang
// Use the specified Username to authenticate the current connection
// with one of the connections defined in the ACL list when connecting
// to a Redis 6.0 instance, or greater, that is using the Redis ACL system.
Username string
```
So before it was just `auth` and the server was happy, now it must be a username known in the ACL system… (Which by default seems to be `default` if that works for you… 🤔)

**Comment by mshedsilegx** [comment]
Yes, exactly, that was my conclusion too.
