### ISSUE TITLE
Türkisch übersetzung 

### ISSUE THREAD

**Issue by vehbiyilmaz** [Luzifer/ots#90]
{
  "alert-secret-not-found": "Aradığınız sır bu değil&hellip; - Sırrın burada olmasını bekliyorsanız, bu link başkası tarafından açılmış ve sırrınız tehlikede olabilir.",
  "alert-something-went-wrong": "Bir şeyler ters gitti. Bunun için çok üzgünüm&hellip;",
  "btn-create-secret": "Sır oluştur!",
  "btn-new-secret": "Yeni sır",
  "btn-reveal-secret": "Sırrı göster!",
  "btn-show-explanation": "Nasıl çalışır?",
  "items-explanation": [
    "Bu sayfadaki alana sırrınızı giriniz",
    "Internet tarayıcınız oluşturulan şifre yardımı ile sırrınızı enkripte eder",
    "Sadece ektripte edilmiş sır sunucuya gönderilir (ne sır metni nede şifre gönderilmez!)",
    "Sunucu enkripte edilmiş sırrı bünyesinde belli bir süre saklar",
    "Gösterilen linki, id ve deşifre bilgisi ile birlikte alıcıya gönder",
    "Alcı sırrı tam olarak sadece bir kez görebilir: Eğer göremez ise, sır bir başkası tarafından daha önce görülmüş olabilir!",
    "Sır bir kez gösterildikten sonra hemen sunucudan silinir"
  ],
  "label-secret-data": "Sır bilgisi:",
  "text-burn-hint": "Lütfen linki kendiniz acmayın, bu sırrın silinmesine neden olur. Linki sadece alıcıya gönderin!",
  "text-hint-burned": "<strong>Dikkat:</strong> Bunu sadece bir kez göreceksiniz. Sayfayı güncellediğinizde yada kapattiğınızda sır kaybolacaktır, belkide şimdi sırrı kopyalamanız akıllıca olacaktır.&hellip;",
  "text-powered-by": "Destekçi",
  "text-pre-reveal-hint": "Sırrı görmek için bu düğmeye tıklayın, ama bunu yaptıktan sonra sırrın silineceğini unutmayın. Bunu sadece bir kez görebilirsin!",
  "text-pre-url": "Sırrınız oluşturuldu ve bu link kullanılarak kaydedildi:",
  "title-explanation": "Bu sekilde çalışır&hellip;",
  "title-new-secret": "Yeni sır oluştur",
  "title-reading-secret": "Sırrınız okunuyor&hellip;",
  "title-secret-created": "Sır oluşturuldu!"
}

**Comment by Luzifer** [comment]
Thank you for taking the time to add an Turkish translation!

One little thing occurred to me when throwing the translation into DeepL (just to be sure not to add something fishy):

> "text-powered-by": "Destekçi",

Was translated by DeepL as "Supporter" or "Backer" but is more meant as "this application is running program OTS"… Literally translating "Powered by" yields "Tarafından desteklenmektedir" or "Tarafından güçlendirilmiştir"… Would that be a better match to express the intention?

**Comment by vehbiyilmaz** [comment]
yes in this case ... Tarafından desteklenmektedir. (.supported or powered
by ) But in Script <translation> by .... thats why i ve used "destekci"
(Supporter)

best sentence is "OTS  arafından desteklenmektedir. "

MfG
vehbi
