### ISSUE TITLE
Enhancement request: Copybutton for convenient sharing of url

### ISSUE THREAD

**Issue by HappyMan4** [Luzifer/ots#91]
Hi Luzifer, would it be possible to have a button "Copy" or "Copy to clipboard" to the left side of the QR code button?
This would be a huge benefit for the mouse-only people who are not so familiar with ctrl-c / ctrl-v.
Just as an idea, maybe fot future versions. 😊

**Comment by Luzifer** [comment]
Will be in next release… 🙂 
![image](https://github.com/Luzifer/ots/assets/20142/fffbe7b0-ddd8-45da-a7d8-adb10b952aa0)

**Comment by HappyMan4** [comment]
Thank you, very much appreciated! ✅😊👍
