### ISSUE TITLE
Manual docker build fails

### ISSUE THREAD

**Issue by nullinger** [Luzifer/ots#96]
Hi,

thank you for this great application!

I tried to manually build the docker container under Ubuntu 22.04 but it seems to fail with an error:
```
docker build -f Dockerfile.minimal .
```
> node: error while loading shared libraries: libicui18n.so.73: cannot open shared object file: No such file or directory
> make: *** [Makefile:15: generate-inner] Error 127

The fix for me was to update both Dockerfiles and add the option `-u` to the pacman command as described on [Stackoverflow](https://stackoverflow.com/a/67552506):
```Dockerfile
RUN set -ex \
 && pacman --noconfirm -Syyu \
...
```

Can you confirm the issue and the simple fix?

Thank you

**Comment by Luzifer** [comment]
Sadly this happens sometimes as Arch is a rolling-release system… And while I cannot recommend using `-u` in the command - at least not by default - as this might cause additional trouble I've rebuilt the upstream image and the build is working again without modifications.

**Comment by nullinger** [comment]
Works, thank you
