### ISSUE TITLE
Formal / Informal German language

### ISSUE THREAD

**Issue by nullinger** [Luzifer/ots#97]
Hi,

it seems that the language of OTS depends on the browser.
Would it be possible to also implement formal German texts, e. g. „Sie“ instead of „Du“?
Maybe with a new parameter in `customize.yaml`?

I can provide all texts if needed.

Thank you

**Comment by Luzifer** [comment]
Interesting request… I see the reasoning for this especially in corporate / enterprise environments where people still feel offended by informal language… 🤔 

Sadly there is no difference between informal and formal German in regards to the browser settings or language code. Both will be `de-DE` and therefore collide. So to provide both in one the generated language file would need a switch which version of the strings to register **before** the application is loaded.

Having the customizations this would be possible I think… 🤔 

Need to have a look how to implement this properly but should be possible.

**Comment by Luzifer** [comment]
@nullinger please have a look at the translations in commit 0903cc2 and the changes in PR #98 - This introduces formal German translations to be triggered through a customization flag.
